apiVersion: v1
data:
  TTAPI_AUTH: AUTHTOKEN
  TTAPI_USER_ID: USER_ID
  TTAPI_ROOM_ID: ROOM_ID
kind: ConfigMap
metadata:
  name: cowgod-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowgod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowgod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowgod
      name: cowgod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cowgod-config
        image: index.docker.io/nugget/cowgod:latest
        imagePullPolicy: Always
        name: cowgod
